apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-config
    labels:
        app: postgres
data:
    POSTGRES_DB: django_db
    POSTGRES_HOST: postgres-service
    POSTGRES_PORT: "5432"
    DJANGO_DEBUG: "True"
    DJANGO_ALLOWED_HOSTS: "*"
